### ISSUE TITLE
Filename too long on checkout

### ISSUE THREAD

**Issue by ckuethe** [ryannining/karyacnc#5]
Looks like `websocket.js`, `3d.html` and `inkscape/laser.py` are symlinks whose filenames are actually the file contents.

**Comment by ryannining** [comment]
hmm, need to check that

**Comment by ckuethe** [comment]
Any chance to look at this? Here's what it does on my machine... https://gist.github.com/ckuethe/0b760b05a5026059984634f2685550b7

**Comment by ckuethe** [comment]
Almost fixed. `websocket.js` is still a symlink instead of a regular file.

**Comment by ckuethe** [comment]
Fixed!
